defaults:
  - schema
  - _self_

# model attributes
base_model: gated_gcn
gine_model_bn: false
pe_method: spe
n_node_types: 9
n_edge_types: 3
node_emb_dims: 90
pooling: add

phi_model_name: gin
pe_dims: 37
n_phi_layers: 9
phi_hidden_dims: 37

#### DOESNT MATTER ####
psi_model_name: mlp
n_psis: 14
n_psi_layers: 3
psi_hidden_dims: 16
psi_activation: relu
num_heads: 4
pe_aggregate: add
#### DOESNT MATTER ####

n_base_layers: 8
base_hidden_dims: 90

n_mlp_layers: 2
mlp_hidden_dims: 70
mlp_use_bn: true
mlp_use_ln: false
mlp_activation: relu
mlp_dropout_prob: 0

residual: true
graph_norm: false
batch_norm: true

# data attributes
use_subset: true
train_batch_size: 100
val_batch_size: 100

BASIS: true
num_samples: 200
RAND_k: 1
RAND_mlp_nlayers: 1
RAND_mlp_hid: 37
RAND_mlp_out: 37
RAND_act: relu
RAND_LAP: None

# optimizer attributes
lr: 0.001
weight_decay: 0.000003
momentum: 0.9
nesterov: false
target_dim: 11

# scheduler attributes
n_warmup_steps: 100

# miscellaneous
n_epochs: 1400
out_dirpath: out/baseline
wandb: True
wandb_run_name: gated_gcn_9:37_8:90
