defaults:
  - schema
  - _self_

# model attributes
base_model: pna_molhiv
gine_model_bn: False
pe_method: spe
n_node_types: 9   # based on https://github.com/pyg-team/pytorch_geometric/files/7494194/README.txt
n_edge_types: 3
node_emb_dims: 80
pooling: add

phi_model_name: gin
pe_dims: 37   # based on SignNet and BasisNet paper (Table 1)
n_phi_layers: 5
phi_hidden_dims: 40

#### DOESNT MATTER ####
psi_model_name: mlp
n_psis: 16
n_psi_layers: 3
psi_hidden_dims: 16
psi_activation: relu
num_heads: 4
pe_aggregate: add
#### DOESNT MATTER ####

n_base_layers: 2
base_hidden_dims: 128
target_dim: 1

n_mlp_layers: 3
mlp_hidden_dims: 128
mlp_use_bn: true
mlp_use_ln: false
mlp_activation: relu
mlp_dropout_prob: 0.3

residual: true
graph_norm: false  # ONLY USED FOR PNA BASE
batch_norm: True   # ONLY USED PHI GIN and PNA BASE

# data attributes
use_subset: True
train_batch_size: 128
val_batch_size: 128

BASIS: True # IF TRUE will run using basis vectors, otherwise will use random samples
num_samples: 300
RAND_k: 7
#mlp_nlayers: 0
#mlp_hid: 0
RAND_mlp_nlayers: 1
RAND_mlp_hid: 37    # shape that goes into PHI
RAND_mlp_out: 37
RAND_act: relu
RAND_LAP: None

# optimizer attributes
lr: 1e-2
weight_decay: 3e-6
momentum: 0.9
nesterov: false

# scheduler attributes
n_warmup_steps: 100

# miscellaneous
n_epochs: 200
out_dirpath: out/baseline
wandb: True
wandb_run_name: BASIS_k=7_PNA_DROP=0.3