defaults:
  - schema
  - _self_

# model attributes
base_model: gine
gine_model_bn: False
pe_method: spe
n_node_types: 9   # based on https://github.com/pyg-team/pytorch_geometric/files/7494194/README.txt
n_edge_types: 3
node_emb_dims: 145
pooling: add

phi_model_name: gin
pe_dims: 37   # based on SignNet and BasisNet paper (Table 1)
n_phi_layers: 9
phi_hidden_dims: 37

psi_model_name: mlp
n_psis: 16
n_psi_layers: 3
psi_hidden_dims: 16
psi_activation: relu
num_heads: 4
pe_aggregate: add

n_base_layers: 7
base_hidden_dims: 145
target_dim: 11

n_mlp_layers: 2
mlp_hidden_dims: 130
mlp_use_bn: true
mlp_use_ln: false
mlp_activation: gelu
mlp_dropout_prob: 0.0

residual: true
graph_norm: false  # ONLY USED FOR PNA BASE
batch_norm: True   # ONLY USED PHI GIN and PNA BASE

# data attributes
use_subset: True
train_batch_size: 100
val_batch_size: 100

BASIS: False # IF TRUE will run using basis vectors, otherwise will use random samples
num_samples: 200
RAND_k: 10
#mlp_nlayers: 0
#mlp_hid: 0
RAND_mlp_nlayers: 1
RAND_mlp_hid: 37    # shape that goes into PHI
RAND_mlp_out: 37
RAND_act: relu
RAND_LAP: None

# optimizer attributes
lr: 1e-3
weight_decay: 3e-6
momentum: 0.9
nesterov: false

# scheduler attributes
n_warmup_steps: 100

# miscellaneous
n_epochs: 400
out_dirpath: out/baseline
wandb: True
wandb_run_name: RAND_k=10