defaults:
  - schema
  - _self_

# model attributes
base_model: gine
pe_method: pearl
n_node_types: 39  
n_edge_types: 10
node_emb_dims: 64
pooling: None


sample_aggr_model_name: gin
pe_dims: 32   
n_sample_aggr_layers: 3
sample_aggr_hidden_dims: 64

n_base_layers: 4
base_hidden_dims: 64

n_mlp_layers: 3
mlp_hidden_dims: 64
mlp_use_bn: true
mlp_use_ln: true
mlp_activation: relu
mlp_dropout_prob: 0.1
pe_aggregate: add

residual: true
graph_norm: false
batch_norm: false

# data attributes
use_subset: true
train_batch_size: 32
val_batch_size: 32

# optimizer attributes
lr: 1e-4
weight_decay: 1e-4
momentum: 0.9
nesterov: false

basis: false
num_samples: 200
pearl_k: 16
pearl_mlp_nlayers: 1
pearl_mlp_hid: 32
wandb: True
wandb_run_name: DrugOOD-SIZE
pearl_act: relu
pearl_mlp_out: 32
gine_model_bn: False

# scheduler attributes
n_warmup_steps: 100

# miscellaneous
n_epochs: 200
out_dirpath: out/baseline