defaults:
  - schema
  - _self_

base_model: gine
gine_model_bn: false
pe_method: spe
n_node_types: 9
n_edge_types: 3
node_emb_dims: 135
pooling: add

phi_model_name: gin
pe_dims: 37
n_phi_layers: 9
phi_hidden_dims: 37

psi_model_name: mlp
n_psis: 16
n_psi_layers: 3
psi_hidden_dims: 16
psi_activation: relu
num_heads: 4
pe_aggregate: add

n_base_layers: 6
base_hidden_dims: 135
target_dim: 11

n_mlp_layers: 2
mlp_hidden_dims: 120
mlp_use_bn: true
mlp_use_ln: false
mlp_activation: gelu
mlp_dropout_prob: 0

residual: true
graph_norm: false
batch_norm: true

use_subset: true
train_batch_size: 50
val_batch_size: 50

BASIS: true
num_samples: 200
RAND_k: 1
RAND_mlp_nlayers: 1
RAND_mlp_hid: 37
RAND_mlp_out: 37
RAND_act: relu
RAND_LAP: None

lr: 0.001
weight_decay: 0.000003
momentum: 0.9
nesterov: false

n_warmup_steps: 100

n_epochs: 400
out_dirpath: out/baseline
wandb: true
wandb_run_name: BASIS_k=1_9:40_6:135_NO_DROPOUT
