dataset: REDDIT-BINARY
model:
  class_num: 1 # 1 or 5
  n_out: 1
  gnn_type: PEARL
  num_layers: 6
  num_layers_pe: 4
  hidden_size_3d: 128
  hidden_size: 128
  pool: add
train:
  epochs: 310
  runs: 10
  batch_size: 70
num_samples: 30
wandb: True
run_name: BIN70
project_name: Reddit-BINARY
