dataset: REDDIT-MULTI-5K
model:
  # gnn_type: PPGN
  # num_layers: 1
  # nlayer_inner: 4
  # pool: add
  class_num: 5 # 1 or 5
  n_out: 5
  gnn_type: SignNet
  num_layers: 6
  #nlayer_inner: 1
  pool: add
train:
  epochs: 250
  batch_size: 100
wandb: True
run_name: SignNet-smallest8_B100
project_name: Reddit-MULTI-5K