dataset: ZINC
model:
  # gnn_type: PPGN
  # num_layers: 1
  # nlayer_inner: 4
  # pool: add
  #class_num: None
  gnn_type: SignNet
  num_layers: 6
  num_layers_sign: 6
  hidden_size_3d: 128
  hidden_size: 128
  #nlayer_inner: 1
  pool: add
train:
  epochs: 370
  batch_size: 80
wandb: False
run_name: SignNet-largest8
project_name: SignNet2